# Key 是表情ID, Value 是表情Hash
faces: 
  203172: de0359b402e9c875
  203173: c01f45b9a9c1e400
  203318: cf479e7c6f0cda90
  203319: 757c5a66ca40bab9
  203391: e3f69eada31f5294
  203469: 03ffa370f7e0570d
  203470: 9df977ccd4794f1c
  203764: b89f0b1c321192be
  203857: b21407c20c5597a9
  204020: 89ae01b6bef173ee
  204235: 41ef554fafa04c2d
  204500: 265ad63dff26a8a3
  204640: c20c4db38715c697
  204705: 00ce0e107391a646
  204811: 2cc36e2aaa9c6ece
  205004: 724f54b2b3f38c90
  205061: 1776acfb8054f8b8
  205129: 940ace4d97232549
  205148: 6d334fb573e4bd18
  205242: 8da95ce6841b88bb
  205284: 935be2d807356258
  205510: 049ab4fa1be291cf
  205782: 2608036d23a72681
  206154: adb04f2815302da1
  206296: 0509fe705f0fd64d
  206352: 7d9bbc07ce293e2f
  206372: ecfc925779fa506f
  206732: f45dafcf1804cae2
  206976: 753f520d766feec9
  206993: 91059a4984f182bd
  207070: af6f7e0850c46ec7
  207222: bd71d2d5cc25f9eb
  207399: aee2526b091c00d1
  207738: b76b01ec8710b0f9
  207865: 9fb5ee9294660231
  208070: 36072e78f46c8545
  208145: fa538ccdff18c698
  208165: 6ef02b55fb4e9ab2
  208246: d0df7f6fa8f75f55
  208293: 0ef16448e9a175ca
  208405: af0784e0933b3247
  208406: 350953236ddc143e
  208584: 72e1c9ef0a8199f7
  208672: 87303e3409eaef84
  208870: 0f1b1c61b1ddd151
  209030: 391484b807727128
  209118: 114131ec35b56cfd
  209306: 94bab60029cc1be4
  209571: d98c062cdf877a2f
  209578: d0f95a43b4b9185c
  209583: 4b4fc6ec7911520c
  209610: 14fd7dbc47bb0ff8
# Key 是别名 Value 是干员名
roles: 
  羊: 艾雅法拉
  鳄鱼: 艾丝黛尔
# Key 是别名 Value 是材料名
items: 
  绿管: 晶体元件
# 开启新好友或新群自动蹲饼
auto_add_guard: true